### ISSUE TITLE
vue-sfc-cli  无法使用

### ISSUE THREAD

**Issue by huangjihua** [FEMessage/vue-sfc-cli#88]
Users/hank/.nvm/versions/node/v8.11.0/lib/node_modules/vue-sfc-cli/init.js:30
  } catch {}
          ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by levy9527** [comment]
能否按照模板，提供多一些信息，否则很难提供帮助。
